### ISSUE TITLE
Fatal error, Found nil while unwrapping value

### ISSUE THREAD

**Issue by asn111** [daihase/LSDialogViewController#5] opened 2018-05-17 07:08 UTC
Hi Daisuke, hope you are fine, first of all I thank you for this awesome library, but I am having some issues regarding closing the dialog .. the lines of code below, are the area where app is crashing from file extension of  UIViewController+LSDialogViewController.swift. 

// close dialog.
    func dismissDialogViewController(_ animationPattern: LSAnimationPattern = .fadeInOut) {
        let sourceView: UIView = self.getSourceView()
        let dialogView: UIView = sourceView.viewWithTag(LSDialogViewTag)!

This is specifically where I am finding nil. kindly help me out I am stuck in here for some long. I need to Complete this app soon. Thank you.

  ---->      let overlayView: UIView = sourceView.viewWithTag(LSOverlayViewTag)!

**Comment by daihase** [comment] 2018-05-17 17:07
@asn111 
Thank you for using my library!
About this problem, I thought that this issue is the same as https://github.com/daihase/LSDialogViewController/issues/4.

First of all, did you use Xib to create Dialog? Or did you create it from the code?
Please tell me. Then, in that way I will present a sample for closing the dialog.

In the case of the above crash, it is because sourceView is nil. If there is a SecondViewController which is a dialog, SecondViewController.view will be set in sourceView. So if the dialog is show, sourceView never becomes nil.

**Comment by asn111** [comment] 2018-05-18 06:01
Thankyou for your reply, well I have created dialog using XIb. 
```
let dialogViewController: CustomDialogViewController = CustomDialogViewController(nibName:"checkOut", bundle: nil)
            dialogViewController.delegate = self
            self.presentDialogViewController(dialogViewController, animationPattern: LSAnimationPattern.fadeInOut, completion: { () -> Void in })
```
this is how  I am calling dialog from 1st VC.

**Comment by daihase** [comment] 2018-05-18 16:25
@asn111  
Thank you for the details.
Please wait a moment as we will prepare samples.

**Comment by daihase** [comment] 2018-05-20 04:01
@asn111 
I prepared a sample project using LSDialogViewController. 

→ [Sample](https://github.com/daihase/LSDialogViewControllerWithXib)

And I understood the cause of crashing by making this sample.
Perhaps you call `self.dismissDialogViewController()` with SecondViewController, don't you?
Tap on the background part of SecondViewController to make it dissmiss by the library, but in case of button control it is made to delete by delegate.

See Sample's LSDialogViewControllerIO.swift. Generally, by preparing a protocol, SecondViewController should close from the called FirstViewController.

I think that this problem will be solved by this. 😃

**Comment by daihase** [comment] 2018-05-25 08:45
@asn111 
I think that it doesn't matter that sample is uploaded, so I'll close this issue.
If there is anything you don't understand, please make an issue again.

**Closed as completed by daihase** 2018-05-25 08:45 UTC

**Comment by PrazwolB** [comment] 2019-07-18 08:34
![Screen Shot 2019-07-18 at 2 18 18 PM](https://user-images.githubusercontent.com/20589398/61442254-fa250800-a966-11e9-8775-56c4c20789a7.png)
![Screen Shot 2019-07-18 at 2 18 26 PM](https://user-images.githubusercontent.com/20589398/61442255-fa250800-a966-11e9-97b1-ae465117ef0d.png)

same crash issue for me.
